# Generated by Django 5.1.2 on 2024-11-16 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('crm', models.CharField(default='000000', max_length=20, unique=True, verbose_name='CRM')),
                ('specialty', models.CharField(max_length=255, verbose_name='Especialidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Registro')),
                ('sector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('foto', models.FileField(blank=True, null=True, upload_to='images/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número para Contato')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Término do Atendimento')),
                ('final_status', models.CharField(blank=True, choices=[('alta', 'Alta'), ('enfermaria', 'Enfermaria'), ('internamento', 'Internamento')], max_length=20, null=True, verbose_name='Status Final')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('ticket', models.CharField(max_length=10, unique=True, verbose_name='Senha')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Chamada')),
                ('status', models.CharField(choices=[('pre_triagem', 'Pré-triagem'), ('triagem', 'Triagem'), ('pre_atendimento', 'Pré-atendimento'), ('em_atendimento', 'Em Atendimento'), ('pos_atendimento', 'Pós-atendimento'), ('finalizado', 'Finalizado')], default='pre_triagem', max_length=20, verbose_name='Status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.doctor')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.pacient')),
                ('triage_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages', to='api.nurse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('data_reception', models.DateTimeField(auto_now_add=True, verbose_name='Data de Triagem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='api.nurse')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='api.pacient')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='api.queue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
