# Generated by Django 5.1.2 on 2024-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('foto', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Pacient',
                'verbose_name_plural': 'Pacients',
            },
        ),
    ]
