# Generated by Django 5.1.2 on 2024-11-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('specialty', models.CharField(max_length=255, verbose_name='Especialidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pacient',
            options={},
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='dataNascimento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='pacient',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('ticket', models.CharField(max_length=10, unique=True, verbose_name='Senha')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('prioridade', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.doctor')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.pacient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('data_screening', models.DateTimeField(auto_now_add=True, verbose_name='Data de Triagem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='api.doctor')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='api.pacient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('date_time_start', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('date_time_end', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Término')),
                ('on_service', models.BooleanField(default=True, verbose_name='Em Atendimento')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.doctor')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.pacient')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
