# Generated by Django 5.1.2 on 2024-11-16 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='service',
            name='pacient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.pacient'),
        ),
        migrations.AddField(
            model_name='service',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='api.queue'),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início do Atendimento'),
        ),
    ]
