# Generated by Django 5.1.2 on 2024-11-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=255, verbose_name='Especialidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='pacient',
            options={},
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='dataNascimento',
            new_name='data_nascimento',
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=10, unique=True, verbose_name='Senha')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('prioridade', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacient')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('data_triagem', models.DateTimeField(auto_now_add=True, verbose_name='Data de Triagem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
