# Generated by Django 5.1.2 on 2024-11-06 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_screening_reception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receptions', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receptions', to='api.pacient'),
        ),
    ]
