# Generated by Django 5.1.2 on 2024-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consultation_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='nurse',
            name='coren',
            field=models.CharField(default='000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
