# Generated by Django 5.1.2 on 2024-11-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_medico_doctor_rename_medico_fila_doctor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fila',
            new_name='Queue',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='especialidade',
            new_name='specialty',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='data_nascimento',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='data_criacao',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='paciente',
            new_name='pacient',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='senha',
            new_name='ticket',
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Status')),
                ('data_screening', models.DateTimeField(auto_now_add=True, verbose_name='Data de Triagem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Triagem',
        ),
    ]
