# Generated by Django 5.1.2 on 2024-11-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_fila_queue_rename_nome_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.pacient'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='api.pacient'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Início')),
                ('date_time_end', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Término')),
                ('on_service', models.BooleanField(default=True, verbose_name='Em Atendimento')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.doctor')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.pacient')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
