# Generated by Django 5.1.2 on 2024-11-14 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reception_doctor_alter_reception_pacient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Registro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='prioridade',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='descriptions',
            new_name='observations',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_time_end',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_time_start',
        ),
        migrations.RemoveField(
            model_name='service',
            name='update_at',
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número para Contato'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='queue',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('pre_triagem', 'Pré-triagem'), ('triagem', 'Triagem'), ('pre_atendimento', 'Pré-atendimento'), ('em_atendimento', 'Em Atendimento'), ('pos_atendimento', 'Pós-atendimento'), ('finalizado', 'Finalizado')], default='pre_triagem', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='queue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='reception',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término do Atendimento'),
        ),
        migrations.AddField(
            model_name='service',
            name='final_status',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('enfermaria', 'Enfermaria'), ('internamento', 'Internamento')], max_length=20, null=True, verbose_name='Status Final'),
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início do Atendimento'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='api.pacient'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='service',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AddField(
            model_name='queue',
            name='triage_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages', to='api.nurse'),
        ),
        migrations.AddField(
            model_name='reception',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='api.nurse'),
        ),
    ]
