# Generated by Django 5.1.2 on 2024-11-17 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_nurse_coren_alter_nurse_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nurse'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.doctor'),
        ),
    ]
