# Generated by Django 5.1.2 on 2024-11-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_time_start',
            field=models.DateTimeField(verbose_name='Data e Hora de Início'),
        ),
    ]
