# Generated by Django 5.1.2 on 2024-11-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_queue_nurse_alter_queue_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
