# Generated by Django 5.1.2 on 2024-11-20 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_nurse_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacient',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='data_reception',
            new_name='reception_date',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.pacient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(max_length=20, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='coren',
            field=models.CharField(max_length=20, unique=True, verbose_name='COREN'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='api.nurse'),
        ),
    ]
