# Generated by Django 5.1.2 on 2024-11-20 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_foto_pacient_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='final_status',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='reception_date',
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Consulta'),
        ),
        migrations.AddField(
            model_name='queue',
            name='category',
            field=models.CharField(choices=[('triagem', 'Triagem'), ('atendimento', 'Atendimento'), ('pos_atendimento', 'Pós-Atendimento')], default='triagem', max_length=15, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='reception',
            name='reception_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hora de Recepção'),
        ),
        migrations.AddField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('em_triagem', 'Em Triagem'), ('disponivel_para_atendimento', 'Disponível para Atendimento Médico'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='em_triagem', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacient'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='ticket',
            field=models.CharField(max_length=15, unique=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nurse'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacient'),
        ),
    ]
