# Generated by Django 5.1.2 on 2024-11-24 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_queue_called_at_remove_queue_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='pacient',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='reception_time',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reception',
            name='addictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='data_triagem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reception',
            name='disease_onset',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
        migrations.AddField(
            model_name='reception',
            name='glasgow_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='main_complaint',
            field=models.TextField(default='Sem queixa'),
        ),
        migrations.AddField(
            model_name='reception',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='pain_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='physical_condition',
            field=models.CharField(default='Sem informação', max_length=255),
        ),
        migrations.AddField(
            model_name='reception',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='low', max_length=50),
        ),
        migrations.AddField(
            model_name='reception',
            name='queue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='api.queue'),
        ),
        migrations.AddField(
            model_name='reception',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='triagem_finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
